map:
  map_type: 42 # 0: Cuboids 1: Bridge

fsm:
  waypoint_num : 3
  # [x, y, theta1, theta2, theta3, theta4, theta5, theta6]
  # [x, y, pitch1, pitch2 , theta3, theta4, theta5, theta6]
  # ###################################### map type 0 forest ######################################
  # init_state             : [-3.0, 0.0, 0.0, -70.0, 110.0, 0.0, -110.0, 0.0] # FastArm
  # init_state             : [-3.0, 0.0, 0.0, -110.0, 70.0, -110.0, -90.0, 0.0] # UR5e

  init_state             : [-3.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  init_yaw               : 90.0
  init_gripper_close     : false

  # Travel to table 1 (target: 0, -3) always facing the table
  waypoint0              : [-1.0, -2.0, 0.0, -110.0, 70.0, -110.0, -90.0, 0.0]
  waypoint0_yaw          : -90.0
  waypoint0_gripper_close: true

  waypoint1              : [0.0, -2.0, 0.0, -110.0, 70.0, -110.0, -90.0, 0.0]
  waypoint1_yaw          : -90.0
  waypoint1_gripper_close: true

  # waypoint2              : [1.0, -1.0, 0.0, -110.0, 70.0, -110.0, -90.0, 0.0]
  # waypoint2_yaw          : -45.0
  # waypoint2_gripper_close: true

  # Travel to table 2 (target: 2, 0) always facing the table
  waypoint2              : [1.0, 0.0, 0.0, -110.0, 70.0, -110.0, -90.0, 0.0]
  waypoint2_yaw          : 0.0
  waypoint2_gripper_close: true
